server:
  port: 9000
  
spring:
  cloud:
    gateway:
      routes:
        #Route Mapping
      - id: UserApplication               #RouteIdentifier
        uri: http://localhost:8761/         #Respective microservice URL which needs to be mapped
         #Request Context Path Mapping
        predicates:
        - Path=/user/**  
         #Route Mapping
      - id: FeignApplication               #RouteIdentifier
        uri: http://localhost:8086/         #Respective microservice URL which needs to be mapped
         #Request Context Path Mapping
        predicates:
        - Path=/demo/**        
        


      